modules:
  instrument: bsdev

# Control detail of exception traces in IPython (console and notebook).
# Options are: 'Plain', 'Context', 'Verbose', 'Minimal', 'Docs'
XMODE_DEBUG_LEVEL: Plain
# Log when devices are added to console (__main__ namespace)
MAKE_DEVICES:
    LOG_LEVEL: info
